### ISSUE TITLE
Anyone receiving timeout errors?

### ISSUE THREAD

**Issue by kenboslice925** [briansrls/Robinhood-for-Google-Finance#13]
I just came across this solution yesterday. After I input my username and password the call is made (which is taking upwards of 1-2 minutes) before throwing the below time out issue. 

Wondering if it's a proxy issue local to my machine. 

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by briansrls** [comment]
Hello,

In your comment you started with, 

> I just came across this solution yesterday.

Was that just a typo?  I will try and see if I get the same error as you.

Please let me know what happens when you navigate to https://api.robinhood.com (in a browser).  Are there any errors?  Does it spin forever?  Does the page load with any information?

Thanks!

**Comment by kenboslice925** [comment]
Thanks for the reply and prompt assistance! that comment was redundant, sorry about that. I basically meant that I came across this Python-based solution yesterday and was not sure if it was still relevant, though it appears to be.

Browsing to api.robinhood.com throws no errors. It loads a packet that appears to contain all the various API calls and their endpoints.  I've included it below:

{"mfa":"https:\/\/api.robinhood.com\/mfa\/","margin_interest_charges":"https:\/\/api.robinhood.com\/cash_journal\/margin_interest_charges\/","margin_upgrades":"https:\/\/api.robinhood.com\/margin\/upgrades\/","instruments":"https:\/\/api.robinhood.com\/instruments\/","quotes":"https:\/\/api.robinhood.com\/quotes\/","accounts":"https:\/\/api.robinhood.com\/accounts\/","orders":"https:\/\/api.robinhood.com\/orders\/","subscription_fees":"https:\/\/api.robinhood.com\/subscription\/subscription_fees\/","id_documents":"https:\/\/api.robinhood.com\/upload\/photo_ids\/","portfolios":"https:\/\/api.robinhood.com\/portfolios\/","markets":"https:\/\/api.robinhood.com\/markets\/","wire_relationships":"https:\/\/api.robinhood.com\/wire\/relationships\/","ach_queued_deposit":"https:\/\/api.robinhood.com\/ach\/queued_deposit\/","subscriptions":"https:\/\/api.robinhood.com\/subscription\/subscriptions\/","wire_transfers":"https:\/\/api.robinhood.com\/wire\/transfers\/","dividends":"https:\/\/api.robinhood.com\/dividends\/","notification_settings":"https:\/\/api.robinhood.com\/settings\/notifications\/","applications":"https:\/\/api.robinhood.com\/applications\/","user":"https:\/\/api.robinhood.com\/user\/","ach_relationships":"https:\/\/api.robinhood.com\/ach\/relationships\/","ach_deposit_schedules":"https:\/\/api.robinhood.com\/ach\/deposit_schedules\/","ach_iav_auth":"https:\/\/api.robinhood.com\/ach\/iav\/auth\/","notifications":"https:\/\/api.robinhood.com\/notifications\/","ach_transfers":"https:\/\/api.robinhood.com\/ach\/transfers\/","positions":"https:\/\/api.robinhood.com\/positions\/","watchlists":"https:\/\/api.robinhood.com\/watchlists\/","document_requests":"https:\/\/api.robinhood.com\/upload\/document_requests\/","edocuments":"https:\/\/api.robinhood.com\/documents\/","password_reset":"https:\/\/api.robinhood.com\/password_reset\/request\/","password_change":"https:\/\/api.robinhood.com\/password_change\/"}

**Comment by briansrls** [comment]
That's good that the api seems to be working correctly.  

I think I understand what you mean, you're referring to this project as a solution to exporting trades to a csv file.  In other words, you haven't found a solution to your issue yet.

I will try to see if I get the same error.  Just out of curiosity, do you have 2fa on your account?

**Comment by kenboslice925** [comment]
Exactly, my hope was this project would allow me to export my trade history into a CSV file. I should've been more clear. 

I do not currently have 2fa

**Comment by jagadeeshpuvvula** [comment]
I'm facing the same issue

**Comment by medici89** [comment]
I'm also facing a timeout error. Although I can't see an error message, the window closes out after I've logged my credentials. I've confirmed that both python and pip are installed to path. Credentials are also correct.

**Comment by briansrls** [comment]
I have a fix in place that seems to work.  I was able to use a lot of the code found at https://github.com/Jamonek/Robinhood and the result seems good.  However, 2fa doesn't seem to work right now.  I'm hesitant to push because I'm sure it will encourage people to disable 2fa.  I'll keep it in my dev branch if you'd like to try it.

**Comment by briansrls** [comment]
https://github.com/briansrls/Robinhood-for-Google-Finance/pull/14

**Comment by briansrls** [comment]
I've pushed my changes to master.  Please try re-pulling the latest changes and let me know if you still have any issues.
