### ISSUE TITLE
Partially Executed Orders

### ISSUE THREAD

**Issue by briansrls** [briansrls/Robinhood-for-Google-Finance#2]
To quote an example from [Here](https://www.reddit.com/r/RobinHood/comments/5g0w86/robinhood_to_google_finance/daq33wa/)

> For example, I placed buy limit order of 2000 shares. The buy order was partially executed for 1700 shares initially, and then remaining 300 shares got bought a few minutes later. The exported transaction in csv only reports a buy transaction of 1700 shares.

**Comment by quanturium** [comment]
This should be fixed when #3 gets merged
