### ISSUE TITLE
Symbol caching is not efficient 

### ISSUE THREAD

**Issue by wezzybytes** [briansrls/Robinhood-for-Google-Finance#9]
`fields[n]['symbol'] = cached_instruments.get(order['instrument'], robinhood.get_custom_endpoint(order['instrument'])['symbol'])`

Second argument to .get() always gets evaluated, therefor it always ends up fetching data for the instrument.

**Comment by briansrls** [comment]
Thanks so much.  Sorry for the delay, I am hoping to get to reviewing this on the weekend :)  Will let you know.

**Comment by briansrls** [comment]
I've had to change the script fundamentally.  Let me know how quickly it grabs your trades, mine fetch in only a couple seconds now.  Obviously your changes will refer to an older commit so you may want to see what has changed.
